### ISSUE TITLE
Add the following places to the production database

### ISSUE THREAD

**Issue by Grunkhead** [wtfloris/hestia#27]
Not sure, if all of them are missing.

's-Gravenzande
Monster
Westland (region)
Naaldwijk
Maassluis
Poeldijk
Hoek van Holland
De Lier
Schipluiden
Honselersdijk
Kwintsheul
Poeldijk
Ter Heijde
Wateringen
Maassland

**Comment by wtfloris** [comment]
As the `/filter city` help message states: cities are added based on scraping results, not manually.

Either way, the plan is to remove the "possible cities" list altogether and just allow users to do text-based filtering, as it allows for more flexibility.
