### ISSUE TITLE
Toevoegen Sites? 

### ISSUE THREAD

**Issue by koenco007** [wtfloris/hestia#37]
Is het mogelijk om meer sites toe te voegen als gebruiker?

**Comment by wtfloris** [comment]
In principe is het mogelijk om een parser te schrijven voor een nieuwe website (zie hestia.py) en een pull request in te dienen, maar ik heb op m'n lijstje staan om nog een korte handleiding hiervoor in de README te zetten.

Welke site zou je willen? Ik zal m op de todo zetten maar kan helaas niks beloven qua wanneer ik tijd ga hebben.

**Comment by koenco007** [comment]
Ik zou rebohuurwoning.nl toe willen voegen. En ook heel erg bedankt voor het bouwen van deze bot!

**Comment by wtfloris** [comment]
Fixed in https://github.com/wtfloris/hestia/pull/39
