### ISSUE TITLE
Doet het niet meer?

### ISSUE THREAD

**Issue by Madiwoedo** [wtfloris/hestia#38]
Hoi Floris,

Ten eerste dankjewel voor het maken van deze bot, hij heeft me in het begin een paar bezichtigingen opgeleverd.
Kan het zo zijn dat er iets is veranderd? Hij doet het de afgelopen tijd niet echt meer. 
Appartementen die binnen de criteria vallen op bijvoorbeeld Pararius verschijnen niet meer in de chat met de bot.

Ik hoor graag van je! Alvast bedankt,
Laurens

**Comment by wtfloris** [comment]
Hoi,

Volgens mij doet de bot het nog, je kan even proberen de commands /stop en /start te gebruiken, kijken of dat helpt.

Pararius is wel een bijzondere, want volgens mij kon je daar niet sorteren op “laatst toegevoegd”. Ik scrape daarom de eerste paar pagina’s maar denk dat ze het niet waarderen als ik alle 100 pagina’s iedere 5 minuten scrape, het kan dus zijn dat er een paar doorheen glippen. 

Succes met de zoektocht in ieder geval!
