### ISSUE TITLE
Optie om specifieke bron weg te filteren

### ISSUE THREAD

**Issue by WybeBosch** [wtfloris/hestia#44]
Hey Floris, 

Het toevoegen van Woningnet bij de websites was een goeie optie, ik merk echter dat deze erg veel woningen weer geeft, 
en gezien bij woningnet de criteria erg streng zijn of je er wat aan hebt (wat betreft positie, inkomen etc.) en zijn de meeste woningen niet relevant.

Kan er een optie zijn om misschien het onderstaande toe te voegen?
```
/filter websites remove utrecht.mijndak.nl
```

Dat je dus specifieke bronnen zelf wel of niet kunt besluiten om te tonen? Ik gebruikte hestia voorheen vooral voor middenhuur, en lette dan zelf op woningnet op wat betreft sociale huur.

**Comment by wtfloris** [comment]
Hi Wybe,

Dank voor je suggestie! Ik heb al enkele berichtjes gehad met dit verzoek dus hij staat hoog op de prioriteitenlijst. Ik hou dit issue up-to-date voor de geïnteresseerden.

**Comment by wtfloris** [comment]
bing bong #45
